version: '3'
services:
  server:
    env_file:
      - .env  # Use ${<VAR>} to get variables from .env file
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${PGUSER}:${PGPASS}@fashion-db.cvaf5upt6dkf.us-east-2.rds.amazonaws.com:5432/postgres?sslmode=require
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: app_user  # In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000/"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
